version: '3.8'

services:
  strapi:
    image: strapi/strapi
    env_file: .env
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./app:/srv/app
    ports:
      - target: 1337
        published: $STRAPI_PUBLIC_PORT

  mongo:
    image: mongo
    env_file: .env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./data/db:/data/db
    ports:
      - target: 27017
        published: $MONGO_PUBLIC_PORT
